class Data {
  String nama;
  String harga;
  String jenis;
  String tipe;
  String plat;
  String warna;
  String tahun;
  String foto;
  String seat;
  String brand;

  Data({
    required this.nama,
    required this.harga,
    required this.jenis,
    required this.tipe,
    required this.plat,
    required this.warna,
    required this.tahun,
    required this.foto,
    required this.seat,
    required this.brand,
  });
}

var veh = [
  Data(
    nama: 'Avanza',
    harga: '100000000',
    jenis: 'SUV',
    tipe: 'SmartCar',
    plat: 'BG 10 TZY',
    warna: 'Maroon',
    tahun: '2020',
    foto: 'asset/images/jalan-asia-afrika.jpg',
    seat: '4',
    brand: 'Toyota',
  ),
  Data(
    nama: 'Alya',
    harga: '100000000',
    jenis: 'SUV',
    tipe: 'SmartCar',
    plat: 'BG 10 TZY',
    warna: 'Maroon',
    tahun: '2020',
    foto: 'asset/images/dua.webp',
    seat: '4',
    brand: 'Toyota',
  ),
  Data(
    nama: 'Agya',
    harga: '100000000',
    jenis: 'SUV',
    tipe: 'SmartCar',
    plat: 'BG 10 TZY',
    warna: 'Maroon',
    tahun: '2020',
    foto: 'asset/images/taman-film.jpg',
    seat: '4',
    brand: 'Toyota',
  ),
  Data(
    nama: 'Xenia',
    harga: '100000000',
    jenis: 'SUV',
    tipe: 'SmartCar',
    plat: 'BG 10 TZY',
    warna: 'Maroon',
    tahun: '2020',
    foto: 'asset/images/jalan-asia-afrika.jpg',
    seat: '4',
    brand: 'Toyota',
  ),
  Data(
    nama: 'Veloz',
    harga: '100000000',
    jenis: 'SUV',
    tipe: 'SmartCar',
    plat: 'BG 10 TZY',
    warna: 'Maroon',
    tahun: '2020',
    foto: 'asset/images/jalan-asia-afrika.jpg',
    seat: '4',
    brand: 'Toyota',
  ),
  Data(
    nama: 'Hino',
    harga: '100000000',
    jenis: 'SUV',
    tipe: 'SmartCar',
    plat: 'BG 10 TZY',
    warna: 'Maroon',
    tahun: '2020',
    foto: 'asset/images/jalan-asia-afrika.jpg',
    seat: '4',
    brand: 'Toyota',
  ),
  Data(
    nama: 'Ship',
    harga: '100000000',
    jenis: 'SUV',
    tipe: 'SmartCar',
    plat: 'BG 10 TZY',
    warna: 'Maroon',
    tahun: '2020',
    foto: 'asset/images/jalan-asia-afrika.jpg',
    seat: '4',
    brand: 'Toyota',
  ),
  Data(
    nama: 'Xpander',
    harga: '100000000',
    jenis: 'SUV',
    tipe: 'SmartCar',
    plat: 'BG 10 TZY',
    warna: 'Maroon',
    tahun: '2020',
    foto: 'asset/images/jalan-asia-afrika.jpg',
    seat: '4',
    brand: 'Toyota',
  ),
  Data(
    nama: 'Pajero',
    harga: '100000000',
    jenis: 'SUV',
    tipe: 'SmartCar',
    plat: 'BG 10 TZY',
    warna: 'Maroon',
    tahun: '2020',
    foto: 'asset/images/jalan-asia-afrika.jpg',
    seat: '4',
    brand: 'Toyota',
  ),
  Data(
    nama: 'Alphard',
    harga: '100000000',
    jenis: 'SUV',
    tipe: 'SmartCar',
    plat: 'BG 10 TZY',
    warna: 'Maroon',
    tahun: '2020',
    foto: 'asset/images/jalan-asia-afrika.jpg',
    seat: '4',
    brand: 'Toyota',
  ),
];
